/**
 * Spotify Setup Script
 *
 * One-time setup to authenticate with Spotify and save refresh token.
 * After running this, the server will auto-authenticate on startup.
 *
 * Usage: npx tsx scripts/spotify-setup.ts
 */

import http from 'http';
import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';

// Load existing .env.local if it exists
const envPath = path.join(__dirname, '..', '.env.local');
let envContent = '';
if (fs.existsSync(envPath)) {
  envContent = fs.readFileSync(envPath, 'utf-8');
}

// Extract existing values
function getEnvValue(key: string): string | null {
  const match = envContent.match(new RegExp(`^${key}=(.*)$`, 'm'));
  return match ? match[1] : null;
}

const CLIENT_ID = getEnvValue('SPOTIFY_CLIENT_ID');
const CLIENT_SECRET = getEnvValue('SPOTIFY_CLIENT_SECRET');

if (!CLIENT_ID || !CLIENT_SECRET) {
  console.error('\x1b[31mError: Missing SPOTIFY_CLIENT_ID or SPOTIFY_CLIENT_SECRET in .env.local\x1b[0m');
  console.log('\nAdd these to joey-musselman-site/.env.local:');
  console.log('  SPOTIFY_CLIENT_ID=your_client_id');
  console.log('  SPOTIFY_CLIENT_SECRET=your_client_secret');
  process.exit(1);
}

// Use a callback port that's likely whitelisted in Spotify dashboard
// IMPORTANT: Spotify requires 127.0.0.1 instead of localhost (as of Feb 2025)
const CALLBACK_PORT = 8888;
const REDIRECT_URI = `http://127.0.0.1:${CALLBACK_PORT}/callback`;

const SCOPES = [
  'user-read-playback-state',
  'user-modify-playback-state',
  'user-read-currently-playing',
].join(' ');

const SPOTIFY_AUTH_URL = 'https://accounts.spotify.com/authorize';
const SPOTIFY_TOKEN_URL = 'https://accounts.spotify.com/api/token';

console.log('\n\x1b[36m=== Spotify Setup ===\x1b[0m\n');
console.log('This will open your browser to authenticate with Spotify.');
console.log(`Make sure this redirect URI is in your Spotify app settings:`);
console.log(`\x1b[33m  ${REDIRECT_URI}\x1b[0m\n`);

// Build auth URL
const authParams = new URLSearchParams({
  client_id: CLIENT_ID,
  response_type: 'code',
  redirect_uri: REDIRECT_URI,
  scope: SCOPES,
  show_dialog: 'true',
});

const authUrl = `${SPOTIFY_AUTH_URL}?${authParams.toString()}`;

// Create temporary server to receive callback
const server = http.createServer(async (req, res) => {
  const url = new URL(req.url || '', `http://localhost:${CALLBACK_PORT}`);

  if (url.pathname === '/callback') {
    const code = url.searchParams.get('code');
    const error = url.searchParams.get('error');

    if (error) {
      res.writeHead(200, { 'Content-Type': 'text/html' });
      res.end(`
        <html>
          <body style="font-family: system-ui; padding: 40px; text-align: center;">
            <h1 style="color: #e53e3e;">Authentication Failed</h1>
            <p>Error: ${error}</p>
            <p>You can close this window.</p>
          </body>
        </html>
      `);
      console.error(`\n\x1b[31mAuthentication failed: ${error}\x1b[0m`);
      server.close();
      process.exit(1);
    }

    if (!code) {
      res.writeHead(400, { 'Content-Type': 'text/plain' });
      res.end('Missing authorization code');
      return;
    }

    // Exchange code for tokens
    try {
      console.log('Exchanging code for tokens...');

      const tokenResponse = await fetch(SPOTIFY_TOKEN_URL, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
          Authorization: `Basic ${Buffer.from(`${CLIENT_ID}:${CLIENT_SECRET}`).toString('base64')}`,
        },
        body: new URLSearchParams({
          grant_type: 'authorization_code',
          code,
          redirect_uri: REDIRECT_URI,
        }).toString(),
      });

      if (!tokenResponse.ok) {
        const errorData = await tokenResponse.json();
        throw new Error(errorData.error_description || errorData.error || 'Token exchange failed');
      }

      const tokens = await tokenResponse.json();

      // Save refresh token to .env.local
      const refreshToken = tokens.refresh_token;

      if (!refreshToken) {
        throw new Error('No refresh token received');
      }

      // Update or add SPOTIFY_REFRESH_TOKEN in .env.local
      if (envContent.includes('SPOTIFY_REFRESH_TOKEN=')) {
        envContent = envContent.replace(
          /^SPOTIFY_REFRESH_TOKEN=.*$/m,
          `SPOTIFY_REFRESH_TOKEN=${refreshToken}`
        );
      } else {
        envContent = envContent.trim() + `\n\n# Spotify refresh token (auto-generated by spotify-setup)\nSPOTIFY_REFRESH_TOKEN=${refreshToken}\n`;
      }

      fs.writeFileSync(envPath, envContent);

      res.writeHead(200, { 'Content-Type': 'text/html' });
      res.end(`
        <html>
          <body style="font-family: system-ui; padding: 40px; text-align: center;">
            <h1 style="color: #38a169;">Success!</h1>
            <p>Spotify is now connected. You can close this window.</p>
            <p style="color: #718096; font-size: 14px;">Refresh token saved to .env.local</p>
          </body>
        </html>
      `);

      console.log('\n\x1b[32mSuccess!\x1b[0m Refresh token saved to .env.local');
      console.log('\nThe server will now auto-authenticate with Spotify on startup.');
      console.log('You can run this script again anytime to re-authenticate.\n');

      server.close();
      process.exit(0);

    } catch (err) {
      res.writeHead(500, { 'Content-Type': 'text/html' });
      res.end(`
        <html>
          <body style="font-family: system-ui; padding: 40px; text-align: center;">
            <h1 style="color: #e53e3e;">Error</h1>
            <p>${err instanceof Error ? err.message : 'Unknown error'}</p>
            <p>You can close this window.</p>
          </body>
        </html>
      `);
      console.error('\n\x1b[31mError:\x1b[0m', err instanceof Error ? err.message : err);
      server.close();
      process.exit(1);
    }
  } else {
    res.writeHead(404);
    res.end('Not found');
  }
});

server.listen(CALLBACK_PORT, () => {
  console.log(`Listening on port ${CALLBACK_PORT}...`);
  console.log('Opening browser...\n');

  // Open browser
  const platform = process.platform;
  try {
    if (platform === 'win32') {
      execSync(`start "" "${authUrl}"`);
    } else if (platform === 'darwin') {
      execSync(`open "${authUrl}"`);
    } else {
      execSync(`xdg-open "${authUrl}"`);
    }
  } catch {
    console.log('Could not open browser automatically.');
    console.log('Please open this URL manually:');
    console.log(`\x1b[36m${authUrl}\x1b[0m\n`);
  }
});

// Timeout after 2 minutes
setTimeout(() => {
  console.log('\n\x1b[33mTimeout: No response received after 2 minutes.\x1b[0m');
  server.close();
  process.exit(1);
}, 120000);
